struct spinlock;
const char* boot_banner(void);
void console_putchar(int);
void console_write(const char*, int);
void shutdown(void);
void kernel_main(void);
void* memset(void*, int, uint);
int strlen(const char*);
void* kalloc(void);
void kfree(void*);
void kinit(void);
void kvminit(void);
void kvminithart(void);
void consoleinit(void);
void uartinit(void);
void plicinit(void);
void plicinithart(void);
void printkinit(void);
int printk(char*, ...);
